#!/usr/bin/env bash
# Build dist/windows-selfhost-kit.md: ONE markdown file holding the README (tutorial) and
# every kit file, for pasting into an AI chat or sending to someone.
#
#   tools/bundle.sh            (re)generate dist/windows-selfhost-kit.md
#   tools/bundle.sh --check    fail if dist/ is out of date or the kit breaks a rule
#
# Rules enforced: every kit file is listed in tools/bundle.manifest, is ASCII-only, has
# LF line endings and ends with a newline; the README variables block equals kit.env.example.
set -euo pipefail
KIT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$KIT"
OUT="dist/windows-selfhost-kit.md"
MODE="${1:-build}"

errors=0
err() { echo "bundle: $*" >&2; errors=$((errors + 1)); }

mapfile -t FILES < <(grep -vE '^[[:space:]]*(#|$)' tools/bundle.manifest)

# ---- checks ---------------------------------------------------------------------
for f in README.md "${FILES[@]}"; do
  [ -f "$f" ] || { err "listed but missing: $f"; continue; }
  if LC_ALL=C grep -q $'\r' "$f"; then err "CR (Windows) line endings: $f"; fi
  if LC_ALL=C grep -qP '[^\x00-\x7F]' "$f"; then err "non-ASCII characters: $f ($(LC_ALL=C grep -nP '[^\x00-\x7F]' "$f" | head -1 | cut -c1-60))"; fi
  if [ -s "$f" ] && [ -n "$(tail -c1 "$f")" ]; then err "does not end with a newline: $f"; fi
done
while IFS= read -r f; do
  f="${f#./}"
  printf '%s\n' README.md "${FILES[@]}" | grep -qxF -- "$f" || err "not in tools/bundle.manifest: $f"
done < <(find . -type f ! -path './dist/*' ! -path './.git/*' ! -name 'kit.env' ! -name 'kit.*.env' ! -name '*.bak' ! -name '*.orig' | sort)
grep -q '<!-- BEGIN README -->\|<!-- END README -->' README.md && err "README.md must not contain the bundle markers"
vars="$(awk '/<!-- VARS:BEGIN -->/{f=1; next} /<!-- VARS:END -->/{f=0} f' README.md | grep -v '^```')"
[ "$vars" = "$(cat kit.env.example)" ] || err "README variables block (between VARS:BEGIN/END) differs from kit.env.example"
[ "$errors" = 0 ] || { echo "bundle: $errors problem(s); nothing written." >&2; exit 1; }

# ---- build ------------------------------------------------------------------------
lang_of() {
  case "$1" in
    *.ps1) echo powershell ;; *.sh) echo bash ;; *.yml|*.yaml) echo yaml ;; *.json) echo json ;;
    *.java) echo java ;; *.xml) echo xml ;; *.sql) echo sql ;; *.properties) echo properties ;;
    *Dockerfile) echo dockerfile ;; *.md) echo markdown ;; *) echo text ;;
  esac
}
fence_for() {  # one backtick more than the longest run of backticks in the file (min 3)
  local n
  n="$( { grep -o '`*' "$1" || true; } | awk '{ if (length($0) > m) m = length($0) } END { print m + 0 }')"
  [ "$n" -lt 3 ] && n=2
  printf '%*s' $((n + 1)) '' | tr ' ' '`'
}

sums="$(sha256sum README.md "${FILES[@]}")"
bundle_id="$(printf '%s\n' "$sums" | sha256sum | cut -c1-16)"

build() {
  cat <<EOF
<!-- GENERATED by tools/bundle.sh from the windows-selfhost-kit folder. Do not edit this file by hand. -->
<!-- bundle-id: $bundle_id -->
# windows-selfhost-kit (single-file edition)

## How to use this file

This file is the complete **windows-selfhost-kit**: the tutorial (the README, next) plus
every script and template it uses (section **Files**, ${#FILES[@]} files). The tutorial expects
them in a folder called \`windows-selfhost-kit\` in your Windows user folder
(\`%USERPROFILE%\\windows-selfhost-kit\`).

**Turn this file back into the folder, either way:**

1. **Automatic (recommended).** Save this file as \`%USERPROFILE%\\windows-selfhost-kit.md\`.
   Save the first file below, \`tools/unbundle.ps1\`, as \`%USERPROFILE%\\unbundle.ps1\`. Then in PowerShell:

   \`\`\`powershell
   cd \$env:USERPROFILE
   powershell -NoProfile -ExecutionPolicy Bypass -File .\\unbundle.ps1 .\\windows-selfhost-kit.md
   \`\`\`

   It recreates every file and checks each one against the checksums at the end.
2. **By hand / AI agent.** For every \`### File:\` heading, create that path with exactly the text
   between the code fences (UTF-8 without BOM, LF line endings, keep it ASCII). Then compare
   with the **Checksums** section (\`sha256sum -c\` format).

Then follow the tutorial from **Part A**. AI agents: read "Rules for AI agents" first.

<!-- BEGIN README -->
EOF
  cat README.md
  cat <<EOF
<!-- END README -->

## Files

EOF
  local f fence exe
  for f in "${FILES[@]}"; do
    fence="$(fence_for "$f")"
    case "$f" in *.sh) exe="yes (chmod +x)" ;; *) exe="no" ;; esac
    printf '### File: `windows-selfhost-kit/%s`\n\n' "$f"
    printf 'Save as `windows-selfhost-kit/%s`. LF line endings. Executable: %s.\n\n' "$f" "$exe"
    printf '%s%s\n' "$fence" "$(lang_of "$f")"
    cat "$f"
    printf '%s\n\n' "$fence"
  done
  printf '## Checksums\n\n```text\n%s\n```\n' "$sums"
}

if [ "$MODE" = --check ]; then
  tmp="$(mktemp)"; build > "$tmp"
  if cmp -s "$tmp" "$OUT"; then rm -f "$tmp"; echo "bundle: $OUT is up to date ($bundle_id)"; exit 0; fi
  rm -f "$tmp"; echo "bundle: $OUT is OUT OF DATE. Run tools/bundle.sh" >&2; exit 1
fi
mkdir -p dist
build > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
echo "bundle: wrote $OUT ($(wc -c < "$OUT") bytes, ${#FILES[@]} files + README, id $bundle_id)"
