#!/usr/bin/env bash
# Let this stack's app call another service over mTLS by its name.
# Writes docker-compose.override.yml (machine-local, git-ignored) that maps the peer's
# name to its 100.x tailnet IP inside the Tailscale sidecar; the app shares it.
# The certificate check then matches the name, while traffic goes over the tailnet.
#
#   mtls/add-peer.sh <stack-dir> <peer-service-name> <peer-100.x-ip>
#   e.g. mtls/add-peer.sh ~/apps/orders-svc billing-svc 100.101.2.3
#   The app then calls https://billing-svc:8443/...  (see MtlsConfig.MtlsClients)
#
# Get a peer's IP from its own "scripts/up.sh" output or "scripts/status.sh".
set -euo pipefail
dir="${1:?Usage: add-peer.sh <stack-dir> <peer-name> <peer-ip>}"
name="${2:?Usage: add-peer.sh <stack-dir> <peer-name> <peer-ip>}"
ip="${3:?Usage: add-peer.sh <stack-dir> <peer-name> <peer-ip>}"
[[ "$name" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]] || { echo "Bad peer name: $name" >&2; exit 1; }
[[ "$ip" =~ ^100\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Expected a 100.x.y.z tailnet IP, got: $ip" >&2; exit 1; }
[ -f "$dir/docker-compose.yml" ] || { echo "$dir is not a stack folder" >&2; exit 1; }

f="$dir/docker-compose.override.yml"
marker="# Generated by mtls/add-peer.sh"
if [ -f "$f" ] && ! grep -qF "$marker" "$f"; then
  echo "$f exists and was not created by this script; add the extra_hosts entry by hand." >&2; exit 1
fi
entries="$( { [ -f "$f" ] && grep -oE '"[a-z0-9-]+:[0-9.]+"' "$f" | tr -d '"' || true; } | grep -v "^$name:" || true)"
entries="$(printf '%s\n%s:%s\n' "$entries" "$name" "$ip" | grep . | sort)"
{
  echo "$marker (windows-selfhost-kit). Machine-local; git-ignored."
  echo "# Maps mTLS peer names to their tailnet IPs. The app shares the sidecar's /etc/hosts."
  echo "services:"
  echo "  tailscale:"
  echo "    extra_hosts:"
  while IFS= read -r e; do echo "      - \"$e\""; done <<< "$entries"
} > "$f"
echo "Peers for $(basename "$dir"):"
sed -n 's/^      - /  /p' "$f"
echo "Apply it (recreates the sidecar; name, IP and URL stay the same):"
echo "  cd $dir && scripts/up.sh"
